version: "3.7"

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - 8000:80
    volumes:
      - .:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - apptransac
      - mysql
    networks:
      - networkapp

  myadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: always
    depends_on:
      - mysql
    ports:
      - "81:80"

  mysql:
    image: mysql:8.0.13
    container_name: mysql
    restart: always    
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: resumen_ingreso
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - dbdatalaravel:/var/lib/mysql
    networks:
      - networkapp

  apptransac:
    build:
      args:
        user: laraveluser
        uid: 1000
      context: .
      dockerfile: ./Dockerfile
    container_name: apptransac
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    networks:
      - networkapp

networks: 
  networkapp:

volumes:
  dbdatalaravel: