version: "3.9"

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - 8000:80
    volumes:
      - .:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - apptransac
      - mysql
    networks:
      - networkapp

  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'resumen_ingreso'
      MYSQL_USER: 'userlrvbd'
      MYSQL_PASSWORD: 'passusuario'
      MYSQL_ROOT_PASSWORD: 'desarrollos'
    ports:
      - 3306:3306
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - networkapp
  apptransac:
    build:
      args:
        user: laraveluser
        uid: 1000
      context: .
      dockerfile: ./Dockerfile
    container_name: apptransac
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    networks:
      - networkapp

  php:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: php
    ports:
      - 9000:80
    volumes:
      - .:/var/www/html
    networks:
      - networkapp

networks: 
  networkapp:

volumes:
  dbdatalaravel: